defaults:
  - scope:
      path: ""
    values:
      layout: default

include:
  - _layouts
  - assets

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

url: "https://etjoy82.github.io/Recursive-Intelligence-Expansion"
plugins:
  - jekyll-sitemap
