title: "Recursive Intelligence Expansion Methodology"
description: "RIEM{} + TSL rendered in harmonic webspace"
theme: jekyll-theme-midnight

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
